// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hashs.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getPasswordHash = `-- name: GetPasswordHash :one
SELECT hashed_password
FROM users
WHERE id = $1
`

func (q *Queries) GetPasswordHash(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getPasswordHash, id)
	var hashed_password string
	err := row.Scan(&hashed_password)
	return hashed_password, err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE users
SET hashed_password = $2, updated_at = NOW()
WHERE id = $1
`

type UpdatePasswordHashParams struct {
	ID             uuid.UUID
	HashedPassword string
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.ExecContext(ctx, updatePasswordHash, arg.ID, arg.HashedPassword)
	return err
}
